<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius"
        value="0.1"/>
    <xacro:property name="lidar_height"
        value="0.1"/>
    <xacro:property name="show_lidar_gazebo"
        value="true"/>

    <link name="2d_lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}"
                    length="${lidar_height}"/>
            </geometry>
            <material name="yellow"/>
            <origin xyz="0 0 ${lidar_height / 2.0}"
                rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.1"
                    length="0.1"/>
            </geometry>
            <origin xyz="0 0 ${lidar_height / 2.0}"
                rpy="0 0 0"/>
        </collision>
        <xacro:inertia_cylinder m="0.3"
            r="${lidar_radius}"
            h="${lidar_height}"
            xyz="0 0 ${lidar_height / 2.0}"
            rpy="0 0 0" />
    </link>

    <link name="laser_scan_link"/>

    <joint name="base_lidar_joint"
        type="fixed">
        <parent link="base_link"/>
        <child link="2d_lidar_link"/>
        <origin xyz="0 0 ${base_height}"
            rpy="0 0 0"/>
    </joint>

    <joint name="2d_lidar_laser_scan_joint"
        type="fixed">
        <parent link="2d_lidar_link"/>
        <child link="laser_scan_link"/>
        <origin xyz="0 0 ${lidar_height / 2.0}"
            rpy="0 0 0"/>
    </joint>

    <gazebo reference="laser_scan_link">
        <material>Gazebo/Yellow</material>
        <sensor type="ray"
            name="lds_lfcd_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>${show_lidar_gazebo}</visualize>
            <update_rate>5</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>0.0</min_angle>
                        <max_angle>6.28319</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.120</min>
                    <max>20</max>
                    <resolution>0.015</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="ray_sensor_controller"
                filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <!-- Configure namespace and remap to publish to /ray/pointcloud2 -->
                    <namespace>/ray</namespace>
                    <remapping>~/out:=laser_scan</remapping>
                </ros>
                <!-- Output as a PointCloud2, see above for other types -->
                <output_type>sensor_msgs/LaserScan</output_type>
                <!-- Clip intensity values so all are above 100, optional -->
                <min_intensity>100.0</min_intensity>
                <!-- Frame id for header of output, defaults to sensor's parent link name -->
                <frame_name>laser_scan_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>