# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

image: 
  name: $CI_REGISTRY/grimbergen_robotics/rostemplates:0.0
  entrypoint: [""]

before_script:
  - rosdep update
  - rosdep install --from-paths src/ --ignore-src --rosdistro ${ROS_DISTRO} -y
  - source /opt/ros/humble/setup.bash

build:
  stage: build
  script:
    - colcon build
