
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="mobile_base.xacro"/>
    <xacro:include filename="simple_arm.xacro"/>

    <!-- Link arm to the mobile base -->
    <joint name="mobile_base_arm_base_joint"
        type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="${base_length / 3.0} 0 ${base_height}"
            rpy="0 0 0"/>
    </joint>
</robot>