<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length"
        value="0.6"/>
    <xacro:property name="base_width"
        value="0.4"/>
    <xacro:property name="base_height"
        value="0.2"/>
    <xacro:property name="base_mass"
        value="5.0"/>

    <xacro:property name="wheel_width"
        value="0.05" />
    <xacro:property name="wheel_radius"
        value="0.1" />
    <xacro:property name="wheel_mass"
        value="1.0"/>

    <xacro:property name="caster_radius"
        value="${wheel_radius / 2.0}" />
    <xacro:property name="caster_mass"
        value="0.5"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}"
                rpy="0 0 0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}"
                rpy="0 0 0"/>
        </collision>
        <xacro:inertia_box m="${base_mass}"
            l="${base_length}"
            w="${base_width}"
            h="${base_height}"
            xyz="0 0 ${base_height / 2.0}"
            rpy="0 0 0"/>
    </link>


    <xacro:macro name="wheel_link"
        params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}"
                        length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0"
                    rpy="${pi / 2.0} 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}"
                        length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0"
                    rpy="${pi / 2.0} 0 0"/>
            </collision>
            <xacro:inertia_cylinder m="${wheel_mass}"
                r="${wheel_radius}"
                h="${wheel_width}"
                xyz="0 0 0"
                rpy="${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left"/>
    <xacro:wheel_link prefix="right"/>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 ${- caster_radius / 2.0}"
                rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 ${- caster_radius / 2.0}"
                rpy="0 0 0"/>
        </collision>
        <xacro:inertia_sphere m="${caster_mass}"
            r="${caster_radius}"
            xyz="0 0 ${- caster_radius / 2.0}"
            rpy="0 0 0"/>
    </link>

    <joint name="base_footprint_joint"
        type="fixed">
        <parent link="base_footprint" />
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}"
            rpy="0 0 0"/>
    </joint>

    <!-- Provide side as -1 or 1 depending on left or right -->
    <xacro:macro name="wheel_joint"
        params="prefix side">
        <joint name="base_${prefix}_wheel_joint"
            type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link" />
            <origin xyz="${-base_length / 4.0} ${side * (base_width / 2.0 + wheel_width / 2.0)} 0"
                rpy="0 0 0"/>
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <xacro:wheel_joint prefix="left"
        side="1.0"/>
    <xacro:wheel_joint prefix="right"
        side="-1.0"/>

    <joint name="base_caster_wheel_joint"
        type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-caster_radius / 2.0}"
            rpy="0 0 0"/>
    </joint>

</robot>
